### ISSUE TITLE
Diseño de placa A

### ISSUE THREAD

**Issue by Eddy-Palo** [e2innovation/Proyecto1_GD#6]
Diseñar el circuito eléctrico y PCB que incluya:
- sensor 1
- uC A
- modulo Tx
deben  tener las conexiones necesarias para generar interrupciones y poder transmitir datos entre:
- el sensor 1 al uC A
- el uC A al modulo Tx
Debe tener los pines necesarios para la programación
conector de batería
leds que indique estado

**Comment by greyvidangos** [comment]
**Diseno de placas:**
1: ADXL362(SPI) + MSP340G2553 + XBEE3
    Source: [https://getsdetection.slack.com/archives/CP65P2P2T/p1585698082000100](url)
2: BMA400(I2C) + MSP340G2553 + XBEE3
    Source: [https://getsdetection.slack.com/archives/CP65P2P2T/p1585698168000900](url)
3: BMI270(I2C) + MSP340G2553 + XBEE3
    Source: [https://getsdetection.slack.com/archives/CP65P2P2T/p1585698248001600]url

**Comment by greyvidangos** [comment]
2: BMI270 [SPI] + uC + XBee3: Verificar conneciones  @axel1123  @Bespi123 
[https://getsdetection.slack.com/archives/CP65P2P2T/p1585867487002600](url)

3: BMA400 [SPI] + uC + XBee3: Verificar conneciones  @axel1123  @Bespi123  
[https://getsdetection.slack.com/archives/CP65P2P2T/p1585867532003300](url)
